### ISSUE TITLE
Broken expert database links

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#112]
This issue is to catalog the broken links to expert database entries. We should do something about these as well as inform the databases themselves.

**Comment by blakesweeney** [comment]
http://rnacentral.org/rna/URS00005FDE16/9606

links to:

http://www.lncipedia.org/db/transcript/lnc-C11orf35-1:1

but the gene link works

**Comment by blakesweeney** [comment]
Not sure if this counts as broken but:

http://rnacentral.org/rna/URS000072D7C7/9595

links to:

http://www.ebi.ac.uk/ena/data/view/CABD02430355.1

which has been replaced.

**Comment by blakesweeney** [comment]
This one is a bit questionable as well:

http://rnacentral.org/rna/URS0000016972/6239

should link to transcript: ` C11D2.10` but the link:

http://www.wormbase.org/species/c_elegans/transcript/C11D2.10

doesn't go directly there, just a search page.

**Comment by AntonPetrov** [comment]
All links are working now so closing.
