### ISSUE TITLE
Import Ensembl data

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#117]
We should import all species from Ensembl as an Expert Database using the [public FTP archive](http://www.ensembl.org/info/data/ftp/index.html). 

* don't import pseudogenes
* mouse and human should be tagged GENCODE and Ensembl, other species - just Ensembl

**Comment by AntonPetrov** [comment]
Also see #100 for importing mouse and human

**Comment by blakesweeney** [comment]
Their data looks well organised, hopefully this will be straightforward.

**Comment by AntonPetrov** [comment]
The data have been loaded in a pre-release database.
