### ISSUE TITLE
Import RMDB

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#138]
In order to establish links with RMDB, we need to specify how a canonical sequence in RNAcentral ‘maps on’ to the sequence in RMDB. So far we haven't done any imports based on sequence mapping, but we will implement this approach for importing Rfam predictions. Once this is done, we can use the same procedure for RMDB.

**Comment by blakesweeney** [comment]
https://rmdb.stanford.edu/tools/

**Comment by blakesweeney** [comment]
Closed until this is actionable.
