### ISSUE TITLE
Additional QC checks

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#140]
This is a list of problematic sequences reported by users that should be used for developing new QC steps.

- [ ] This sheep [miRNA 21 sequence]( http://rnacentral.org/rna/URS0000A1EB8F) seems incorrect because it's not like the [miRNA 21 in miRBase](http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0014116) and is not similar to any other miRNA (possible bacterial contamination).

**Comment by nataquinones** [comment]
Sequences from [this publication](http://rnacentral.org/search?q=pub_id:%22199890%22 ), are submitted in **ENA** as ``misc_RNA`` but have ``mol_type="mRNA"``.

Example: [URS00000935D3](http://rnacentral.org/rna/URS00000935D3/2843) (ENA: [AB204782.1:1..305:misc_RNA](http://www.ebi.ac.uk/ena/data/view/Non-coding:AB204782.1:1..305:misc_RNA) )
