### ISSUE TITLE
Issues with the new naming decisions

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#151]
The new naming method doesn't seem to work as desired in some cases. This is really notable in the standard HOTAIR search (http://test.rnacentral.org/search?q=%22HOTAIR%22%20AND%20TAXONOMY:%229606%22%20AND%20rna_type:%22lncRNA%22). This has fewer results than the current production one. Some of the production ones that you may expect to show up don't. Some details are:

This should be called HOTAIR:

http://test.rnacentral.org/rna/URS0000301B08/9606

It has a weird name without HOTAIR in it: `Homo sapiens long non-coding RNA lnc-SMUG1-7:1`. The LNCipedia [URL](http://www.lncipedia.org/db/transcript/lnc-SMUG1-7:1) redirects to HOTAIR.

This should be a lncRNA, not antisense as it is currently listed, and found in the standard HOTAIR search: <http://test.rnacentral.org/rna/URS0000757747/9606>.

This happens (I think) because we are trusting the LNCipedia more than NONCODE (which I agree with). However, we should prefer GENCODE over all others here and this would fix the issue presented. In addition Ensembl should probably be trusted too. This highlights a weakness in the current approach where the logic to define what databases we have is separate from the logic on which one to select. This leads to me forgetting to update bits and is generally bad. I'm not sure what to do between GENCODE and HGNC right now. I am leaning toward trusting GENCODE more as they do have experimental data attached as well. I could make them a tie and then select the best name among the two, though.

This highlights a problem in the current approach where the implementation of what databases to use for descriptions doesn't rely upon what database we know about (expert_databases module), leading to me forgetting to include GENCODE as a choice we prefer. This should be rectified but may be a bit of work.

**Comment by AntonPetrov** [comment]
Exporting `locus_tag` and `standard_name` fields should help 6f4c942bcfb9e3ed78e90fe7880d099098ba1444

**Comment by AntonPetrov** [comment]
This issue can be closed once we confirm that locus_tags are searchable.

**Comment by blakesweeney** [comment]
These appear to be fixed now. Using `locus_tag` in the search now finds reasonable results for the HOTAIR search.
