### ISSUE TITLE
Update PDB literature reference format

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#155]
[In this example](http://rnacentral.org/rna/URS000080DDAA/9606?tab=publications), "Chen J.H" should be a single link, not two separate links "Chen" and "J.H.". The search itself should be just for "Chen", without initials.

This happens because PDB references are in a different format than all other literature reference, with an extra comma after the last name. 

To fix this, we need to update the `download_pdb.py` script in the `rnacentral-import-pipeline` repo.

**Comment by blakesweeney** [comment]
This is fixed with RNAcentral/rnacentral-import-pipeline#6.

**Comment by AntonPetrov** [comment]
Need to check that the fix worked when the new release is loaded.

**Comment by AntonPetrov** [comment]
The fix did work but now the PDB publications are duplicated now:
http://test.rnacentral.org/rna/URS000080DDAA/9606

**Comment by AntonPetrov** [comment]
Closing this. Duplicate publications will be addressed in #199.
