### ISSUE TITLE
Fully automate search dump generation

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#156]
Need to develop a single entry point for generating search dumps.

- [x] launch export
- [x] check logs files
- [ ] generate release_note.txt
- [ ] generate email template and/or send it

**Comment by blakesweeney** [comment]
This is in better shape now. The search export is built but release_note.txt isn't built yet, nor is the email sent. I'm not so sure about sending the email but building release_note.txt is a good goal.

**Comment by AntonPetrov** [comment]
@blakesweeney - can this be closed now?

**Comment by blakesweeney** [comment]
Yes, everything for search export including building the metadata files and placing them in the correct place is automated.
