### ISSUE TITLE
Different results between text box search and API?

### ISSUE THREAD

**Issue by tdido** [RNAcentral/rnacentral-webcode#158]
I built a query that I'd like to use to obtain data programmatically. When I [run it through the UI](http://rnacentral.org/search?q=(rna_type:%22rRNA%22%20OR%20rna_type:%22tRNA%22%20OR%20rna_type:%22snRNA%22%20OR%20rna_type:%22snoRNA%22%20OR%20rna_type:%22miRNA%22)%20AND%20taxonomy:%2210090%22), I get ~13k sequences back. When I [run it through the API](http://rnacentral.org/api/v1/rna/?q=(rna_type:%22rRNA%22%20OR%20rna_type:%22tRNA%22%20OR%20rna_type:%22snRNA%22%20OR%20rna_type:%22snoRNA%22%20OR%20rna_type:%22miRNA%22)%20AND%20taxonomy:%2210090%22&format=json), I am getting ~10M sequences. At first I thought it was not parsing the taxonomy filter, but the UI number you get when you remove the taxonomy is (ever so slightly) different from the one the API is returning.

**Comment by AntonPetrov** [comment]
Unfortunately the RNAcentral API does not support filtering by taxonomy at this time so your second query is based only on RNA types without restricting it to mouse, which is why it returns so many hits. 

If you are interested in running text searches programmatically, you could consider using [EBI search](http://www.ebi.ac.uk/ebisearch/documentation.ebi), which is the same search engine that RNAcentral uses.

For example, here is your query:
```
http://www.ebi.ac.uk/ebisearch/ws/rest/rnacentral?query=(rna_type:"rRNA" OR rna_type:"tRNA" OR rna_type:"snRNA" OR rna_type:"snoRNA" OR rna_type:"miRNA" ) AND TAXONOMY:"10090"&format=json&hlfields=description,length&sort=length:descending
```

Here is a [list of available search fields](http://www.ebi.ac.uk/ebisearch/metadata.ebi?db=rnacentral).

I hope this helps! Please let me know if you need more information.

**Comment by tdido** [comment]
Ah, I see. That works, initially, but I couldn't find any documentation on how to deal with pagination on the EBI search API (the RNAcentral one has the "page" and "page_size" parameters, and the nice "next" attribute in the results). Any pointers for that?

Also, it seems like you can't get the sequence from the EBI search. Is going back to the RNAcentral API with the sequence ID the only way?

**Comment by AntonPetrov** [comment]
You can use URL parameters like `&size=15&start=0` to paginate over the results. The maximum page size is 100 and the total number of results you can iterate over is 250,000.

Also, did you know that you can [download search results](http://www.ebi.ac.uk/training/online/course/rnacentral-exploring-non-coding-rna-sequences/exporting-search-results) in multiple formats, including fasta, from the user interface?

If you need to export data from lots of searches, I will be happy to help if you can describe your use case a bit more.

**Comment by tdido** [comment]
Right, I'll be able to manage it with those parameters.

I did download the data manually, but I'm integrating this into an automated pipeline.

Thanks!

**Comment by AntonPetrov** [comment]
No problem, feel free to let us know if you need anything else!

**Comment by tdido** [comment]
Oh actually, about getting the sequence, do I need to hit the RNAcentral API with the IDs I get from ebisearch?

**Comment by AntonPetrov** [comment]
Yes, you can hit the API, that shouldn't be a problem. 

You can also use Easel `esl-sfetch` command that can quickly retrieve a list of identifiers from a FASTA file containing all RNAcentral sequences. The esl-sfetch command is part of the Infernal software suite, you can see the installation instructions in the RNAcentral [Dockerfile](https://github.com/RNAcentral/rnacentral-webcode/blob/master/Dockerfile#L105).
