### ISSUE TITLE
Store RefSeq Gene Ids in a separate column

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#160]
Right now they are stored in `db_xref` along with other text. Once done, revert changes from this commit: b7c2616

**Comment by AntonPetrov** [comment]
I updated the import pipeline to store RefSeq GeneIds in the `optional_id` column. The data have been loaded in _pfmegrnadev_.

@BurkovBA Could you please test if this solves the performance problems with looking up splice variants? Feel free to close this issue when you are done.

**Comment by BurkovBA** [comment]
Awesome, now simple requests to API with a couple of splice variants and a couple of Xrefs overall take ~500 milliseconds. Thanks!
