### ISSUE TITLE
Do not index incorrect RNA types

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#161]
- [x] For example, in this case one ENA accession thinks this is a miRNA although the sequence is >2K long:
http://rnacentral.org/rna/URS0000010D9A/7227
- [x] Not clear why RNA type facet has multiple values (lncRNA, antisense, misc_RNA) for this search: 
http://rnacentral.org/search?q=rna_type:%22lncrna%22
- [x] Use Rfam to detect RNA type inconsistencies
For example, [URS00002639FB/9606](http://rnacentral.org/rna/URS00002639FB/9606) is a tRNA but ENA labels it as rRNA so rRNA is chosen as a type.

**Comment by blakesweeney** [comment]
The example of inconsistent RNA types should have a warning in our current system (missing match) but it does not. I can modify the system to detect this case easily. Previously we would only warn if a sequence had a match to something that was not rRNA or tRNA, but would not warn if the sequence had no matches at all.

**Comment by AntonPetrov** [comment]
Let's try adding this warning and see how well it works. Thank you!
