### ISSUE TITLE
Improve Ensembl import

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#169]
- [x] for GENCODE use Ensembl transcript ids as `Accession.external_id` and keep `OTT` ids in `db_xref`
- [x] detect spelling errors in biotype (e.g. `vaultRNA` instead of `vault_RNA`)
- [x] check why some entries are `antisense_RNA` and others are just `antisense`
- [x] import mouse strains
- [x] stop displaying OTT ids on webpages

**Comment by blakesweeney** [comment]
We decided not to import mouse strains this time. Maybe we should review how to do a good job of this for next release?

**Comment by AntonPetrov** [comment]
Yes, let's review mouse strains for next release and talk with Ensembl people next week. Thank you!

**Comment by blakesweeney** [comment]
These issues appear to be fixed with the latest round of precomputing.
