### ISSUE TITLE
Sequence search results could be improved

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#197]
Currently sequence search results do not show ideal results. The biggest problem is that it isn't easy to figure out what exactly the matched sequence is because the names shown for each result are unclear. For example, searching with the sequence of URS000075DAE, gives the following results:

- Homo sapiens lncRNA URS000075DAEC
- Homo sapiens lncRNA URS0000204428
- Homo sapiens misc RNA URS00005DA113
- Homo sapiens lncRNA URS00008B9A1F

and so forth. It would probably be better to use the species specific names in the case where there is only 1 species for sequence. This would make the result a lot easier to understand. We may want to do this by changing the logic for description selection when there is only 1 species or we may want to just change it for just this page. Either way I think the results will be much more useful if there is the more detailed name present. 

Using the species names if possible does mean that names will change between releases, but that can happen already anyway.

There are some other possible improvements:
- List all species the sequence has been aligned to
- Allow filtering by species
- Provide information about target size.

but I think those could wait a bit.

**Comment by AntonPetrov** [comment]
I agree, this needs to be fixed. The FASTA file currently gets descriptions using `Rna.get_sequence_fasta()`which calls `Rna.get_description()` so these are not species-specific. 

Alternatively, we could consider searching species-specific FASTA file but it has some extra redundancy.

**Comment by AntonPetrov** [comment]
The new beta [sequence search](https://rnacentral.org/sequence-search-beta/) addresses this issue.
