### ISSUE TITLE
Add RNA type to either id_mapping.tsv or description in the fasta files

### ISSUE THREAD

**Issue by dpryan79** [RNAcentral/rnacentral-webcode#20]
While the RNA type (e.g., piRNA or miRNA) is usually discernible from the descriptions in the downloadable fasta header lines, this isn't always the case. Examples of that would include URS000000C8CD, which is just a "non-coding RNA", which isn't exactly informative. Sometimes this can be parsed from the id_mapping.tsv file, but not when the only source is ENA (even when ENA fully annotates an RNA).

Standardizing this in either the fasta description lines or the id_mapping file (or even another file altogether) would both seem to be good solutions.

I should note that I recognize that this may prove to be a royal pain to implement (particularly as more databases are integrated), so perhaps this could get placed on the "rainy day" list of things to do.

**Comment by AntonPetrov** [comment]
ncRNA type is now provided in the id_mapping file (also see discussion in #42):
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/ 

Please feel free to let me know if you have any other suggestions.
