### ISSUE TITLE
Hide Species column on the species-specific URS pages

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#205]
When looking at a species-specific page like [this one](http://rnacentral.org/rna/URS000025784F/9606) there is no need to show redundant links with organism name in the Annotations table. The link needs to be moved to the Overview section.

The column can be still shown on the main URS page (without taxid in the URL).

**Comment by BurkovBA** [comment]
I think, I'd better do this issue after I migrate that page to frontend, cause it would take too much time to sort-out, how to get it working in the old version of dataTables with imperative javascript.

**Comment by BurkovBA** [comment]
Without dataTables this was a piece of cake. Done in #110 branch.
