### ISSUE TITLE
Investigate Google indexing problems

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#212]
When searching on Google for RNAcentral pages only 2,300 pages are found and all of them are not species-specific. 
https://www.google.co.uk/search?q=site:rnacentral.org

Google is crawling the new sitemap with species-specific entries but they don't make into search results. We need to search for potential reasons and raise an issue in the official Google search Google Group.

Turns out, we have `example.com` as the domain in sitemaps - got to fix it and also maybe create a subset of pages, relevant to Human only, then to Human and Mouse and so on, depending on the performance.

- [ ] Add support for Bioschemas (http://bioschemas.org/, https://github.com/BioSchemas, http://schema.org/)
- [x] Add publications tab contents to the bottom of the front page
- [x] Possibly write to Google webmasters support forum
- [ ] Possibly add synonyms to the top of the page
- [ ] Lots of pages are crawled as empty - investigate them and possibly write to Google forums about them

**Comment by blakesweeney** [comment]
I think is fixed now, we have linked data in pages and the google search does show sequence specific results.
