### ISSUE TITLE
Some sequences are all N's

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#219]
We need to scan all sequences to make sure that the rules of no more than 10% N's are respected. Lncipedia, NONCODE and other databases processed as JSON are possibly affected.

Examples of sequences containing only N's:

```
>URS00008BF8C4_9606 Homo sapiens long non-coding RNA lnc-RAB38-3:1
>URS00008B3572_9606 Homo sapiens long non-coding RNA lnc-SLC6A12-8:1
>URS00008BB33A_9606 Homo sapiens long non-coding RNA lnc-DNLZ-3:1
>URS00008BDE4F_9606 Homo sapiens long non-coding RNA lnc-TCTE3-5:1
>URS00008BC78D_9606 Homo sapiens long non-coding RNA lnc-TUBGCP3-18:1
>URS00008B3E48_9606 Homo sapiens long non-coding RNA lnc-NBPF20-3:1
>URS00008BC549_9606 Homo sapiens long non-coding RNA lnc-TUBGCP3-19:1
>URS00008B2707_9606 Homo sapiens long non-coding RNA lnc-AP001631.10.1-2:1
>URS00008B27CD_9606 Homo sapiens long non-coding RNA lnc-C17orf51-18:1
>URS00008B7944_9606 Homo sapiens long non-coding RNA lnc-AL353608.1-3:1
>URS00008B994B_9606 Homo sapiens long non-coding RNA lnc-NOS2-14:1
>URS00008B9962_9606 Homo sapiens long non-coding RNA lnc-FOXD4L6-4:1
>URS00008BE863_9606 Homo sapiens long non-coding RNA lnc-C17orf51-19:1
>URS00008BF460_9606 Homo sapiens long non-coding RNA lnc-MRPS5-17:1
>URS00008BBB79_9606 Homo sapiens long non-coding RNA lnc-RP13-512J5.1.1-3:1
>URS00008BCD30_9606 Homo sapiens long non-coding RNA lnc-NOS2-17:1
>URS00008BCECC_9606 Homo sapiens long non-coding RNA lnc-DNAJC18-2:1
>URS00008BD366_9606 Homo sapiens long non-coding RNA lnc-NOS2-15:1
>URS00008B3802_9606 Homo sapiens long non-coding RNA lnc-APOB-9:1
>URS00008B34E6_9606 Homo sapiens long non-coding RNA lnc-NOS2-16:1
>URS00008B5DC8_9606 Homo sapiens long non-coding RNA lnc-GATA5-3:1
>URS00008B6A42_9606 Homo sapiens long non-coding RNA lnc-MRPS5-18:1
```

**Comment by blakesweeney** [comment]
I spent a little time looking into this and we can find the sequences easily enough. The following queries find 3,039 sequences (most of which are short):

```sql
select 
	count(1)
from rna 
where
	seq_long is not null
	and len - length(replace(seq_long, 'N', '')) > round(0.1 * len)
; -- 3,036
select 
	count(1)
from rna 
where
	seq_short is not null
	and len - length(replace(seq_short, 'N', '')) > round(0.1 * len)
; -- 3
```

I looked at a couple results and they seem correct. It should be pretty simple to validate more sequences. I'm guessing we would use the queries to then find all xrefs and mark them as deleted. That shouldn't be too hard of a query. 

I also think a good general solution to this may be to add a CHECK constraint to the DB. All that is required is probably:

```sql
ALTER TABLE RNA
ADD CONSTRAINT chk_seq_short_N CHECK seq_short is null or len - length(replace(seq_short, 'N', '')) <= round(0.1 * len)
ADD CONSTRAINT chk_seq_long_N CHECK seq_long is null or len - length(replace(seq_long, 'N', '')) <= round(0.1 * len)
;
```

Doing this will make our import pipeline fail if we don't ensure we reject these sequences when processing them which may prove annoying during import. Also, I'm not sure how to encode these constraints in our Django models. Even still it seems useful to me. If you want I can try adding these constraints as part of our next release.

**Comment by blakesweeney** [comment]
I've added the constraints, as well as modified the pipeline code to exclude sequences with this issue. It shouldn't be an issue in the future. Plus I've created a table of these upi's, using:


```sql
create table rna_invalid_sequences (
	upi varchar(30) NOT null references rna(upi) primary key
);

insert into rna_invalid_sequences
select 
	rna.upi
from rna 
join xref on xref.upi = rna.upi
where
	seq_short is not null
	and len - length(replace(seq_short, 'N', '')) > round(0.1 * len)
	and deleted = 'N'
on conflict do nothing

;

insert into rna_invalid_sequences
select 
	rna.upi
from rna 
join xref on xref.upi = rna.upi
where
	seq_long is not null
	and len - length(replace(seq_long, 'N', '')) > round(0.1 * len)
	and deleted = 'N'
on conflict do nothing
;
```

we can use this to mark all xrefs as deleted. I forgot the trick to do this while dealing with the partitions though.

**Comment by blakesweeney** [comment]
Ran this on prod:

```sql
insert into xref
select
	bad.dbid,
	bad.created,
	bad.last,
	bad.upi,
	bad.version_i,
	'Y' deleted,
	bad."timestamp",
	bad.userstamp,
	bad.ac,
	bad.version,
	bad.taxid
from xref bad
join rna_invalid_sequences invalid on invalid.upi = bad.upi
;

delete from xref using rna_invalid_sequences invalid where invalid.upi = xref.upi and deleted = 'N';
```

should clean up all the bad entries. I didn't drop rna_invalid_sequences but we can do so once we are happy with the results.

**Comment by blakesweeney** [comment]
To update this, I have modified the pipeline to reject such sequences as well as added constraints to the database which should prevent the sequences from being present in the future. Post release I'll do another more careful look at this.

**Comment by blakesweeney** [comment]
I think this issue can be closed, the data seems to be cleaned up.
