### ISSUE TITLE
Migrate RNAcentral to HTTPS

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#223]
- [x] come up with a solution for HTTPS (I'd prefer Nginx + uWSGI) - won't do
 - [x] buy and install an SSL certificate
 - [ ] make sure that log collection doesn't break after this
 - [x] make sure that AJAX requests don't break after moving to HTTPS
 - [x] change css selectors in main.css section 4 to color outbound links
 - [x] modify css selector for outbound links for Google Analytics
 - [ ] sitemaps include protocol
-  [x] check that API examples and the GitHub example script are updated

Time estimate: 7 days.

**Comment by AntonPetrov** [comment]
The website works with https since September 3rd, 2018
