### ISSUE TITLE
Make db icons in search link to the database page of the URS

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#235]
For example, going to browse for the first hit (http://rnacentral.org/rna/URS000019E0CD/9606) the ensembl icon should link to: http://www.ensembl.org/Homo_sapiens/Transcript/Summary?t=ENST00000626826.1 (or the gene page if we want to go that direction). This is a suggestion from John at the ncGenome conference.

**Comment by AntonPetrov** [comment]
Some sequences may have several Ensembl links which some users may found confusing.
