### ISSUE TITLE
Clicking the genome checkmark should open the region in UCSC

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#236]
John Rinn suggests that on the search page, the check marks should be clickable and lead to the UCSC browser. We may want to move from checkmarks but into icons for UCSC/ensembl browser and make those icons lead to the correct region in UCSC/Ensembl.

**Comment by AntonPetrov** [comment]
Some people may prefer using Ensembl browser. Also, some sequences may be found in several genome locations so it's not clear where the link would go first. I suggest keeping this functionality in the _Genome location_ section of each page for now and revisit this once we have more genome mapping.
