### ISSUE TITLE
Improving search result sorting

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#240]
It is not great right now. It is too simple. John suggested that we include the number of databases as a criteria, but who knows. I think this will be an ongoing issue but is something we need to address as we work on the site. 

Could creatively copy-paste sort options from Rfam.

Time estimate: 1-3 weeks, depending on degree of our fanaticism.

**Comment by AntonPetrov** [comment]
We can add sorting similar to how it's done in Rfam. Possible sorting options could be: relevance (current default), sequence length

**Comment by BurkovBA** [comment]
This is generally an interesting issue: I believe, we could do some improvements, displaying the search results list. 

I'd take a look at other resource, doing good job at this UI. I'd also ask my friends - I recall some of them coming up with good suggestions previously.

Generally, I'd try making as much of detail page information available in preview as possible, maybe popups or something. This shall arguably decrease page view count, but this will surely increase the amount of our unique users. I believe, this is worth it, let's not buy into http://vooza.com/videos/bullshit-metrics/.
