### ISSUE TITLE
Create JSON schema for data imports

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#264]
We need to create a schema that will enable RNAcentral to accept submissions where a direct submission is warranted (for example, FlyBase or GtRNAdb).

* [GtRNAdb example JSON](https://gist.github.com/AntonPetrov/9ef6c5ab5e280f9fd31d1da4a7908253)
* [Example AGR schema](https://github.com/alliance-genome/agr_schemas/blob/release/1.0.3/basicGeneInformation.json)
* [Example AGR data](https://github.com/alliance-genome/agr_schemas/blob/release/1.0.3/mgiSample.BGI.json)

**Comment by blakesweeney** [comment]
The schema is being developed in https://github.com/RNAcentral/rnacentral-data-schema

**Comment by blakesweeney** [comment]
As an update on this, the schema has been emailed to flybase, gtrnadb, and mirbase. We are currently waiting for feedback and new data to import with it. I will continue with writing code to import the new data, but I feel that without feedback and examples of new data the code will be incomplete.

**Comment by AntonPetrov** [comment]
This has been done: https://github.com/RNAcentral/rnacentral-data-schema
