### ISSUE TITLE
Text search improvements

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#266]
- [x] add a tooltip to Rfam warnings on text search results
- [x] improve size and readability of expert database icons (especially RefSeq, FlyBase and miRBase)
- [x] replace Rfam problems facet with a boolean facet (problems found/not found)

**Comment by BurkovBA** [comment]
Guys, I did my part on this problem. I can help you style the tooltip appearance as soon as the data are in place (although generally I'm not any better with css than you are).

**Comment by AntonPetrov** [comment]
Tooltips are done, the only thing left is to update the facets after the data have been reindexed.
