### ISSUE TITLE
Improve text searches for miRNAs

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#275]
It can be very difficult to find a sequence. For example someone tried to use `rat microRNA 21 AND rna_type:"miRNA"` to find rat microRNA 21 at the recent meeting. This was pretty tricky and I had to do a several searches before I settled on `rno-MiR-21` which finds the sequence (but not in the top 20 hits). Clearly we need to look at how things are matched, or something.

**Comment by AntonPetrov** [comment]
I think this is related to #268 - if we index strings like "mir-21", it will be easier to find entries like this. 

Currently the index contains "rno-mir-21" as one string but the query is "mir-21*", so nothing is found.

**Comment by blakesweeney** [comment]
True, but the original search is a reasonable one for finding mir-21 and doesn't.

**Comment by blakesweeney** [comment]
It is now possible to use `mir-21` and find this sequence, but it doesn't end up in the first few hits. There is more work to do on the result ordering, but at least this can be found.
