### ISSUE TITLE
Extract Ensembl genome information

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#283]
The simplest thing we can do to improve genome mapping is to import Ensembl genome information directly. This will increase the number of genomes we provide coordinates for a lot. Plus this is needed to do genome mapping for sequences in general, no need to map things we already know coordinates for. This will require me to parse Ensembl's API a bit to produce the configuration data. Boris may have to do some logic in the front end to display the new genomes. The script may end up in the import pipeline, but the result will be in webcore.

**Comment by blakesweeney** [comment]
I think this is now done by @BurkovBA as part of the another issue. Is this still needed?

**Comment by BurkovBA** [comment]
Yep, this is done. Thanks for spotting this!
