### ISSUE TITLE
Add PDB chain id to the id mapping file

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#288]
Currently the id mapping file for PDB contains lines like this:

```
URS0000005270	PDB	4V6X	9606	rRNA	
```

This information is not enough to provide links back to RNAcentral because one PDB file may contain several RNA chains.

Example of the mapping file with chain IDs:

```
URS0000005270	PDB	4V6X_1	9606	rRNA	
```

**Comment by blakesweeney** [comment]
This is fixed with the database mapping logic in the release-9 branch.
