### ISSUE TITLE
Import more data on publications from EuropePMC

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#296]
Migrated from #199

- [ ] retrieve missing bibliographic information from EuropePMC (DOI, PubMed IDs etc)
- [ ] connect INSDC submissions with corresponding journal articles using EuropePMC API. Sometimes an entry goes to ENA as INSDC submission and the journal article is published afterwards
- [ ] explore using EBI search index to retrieve publications

Example: [this sequence](http://rnacentral.org/URS00005B5A80/9606) links to an "Unpublished" paper:
<img width="570" alt="screen shot 2018-03-06 at 12 48 44" src="https://user-images.githubusercontent.com/432675/37033122-b9df045c-213c-11e8-894c-b0c24e37ba3f.png">
However, a search in EuropePMC finds a paper with the exact title:
http://europepmc.org/abstract/MED/15199136

**Comment by blakesweeney** [comment]
This is now fixed by LitScan.
