### ISSUE TITLE
rnc_accession.species contains both Gorilla gorilla and Gorilla gorilla gorilla

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#298]
Same story for Ceratotherium simum simum and Ceratotherium simum.

`SELECT * FROM rnc_accessions WHERE rnc_accessions.species='Ceratotherium simum';`

Please, ping me after the fix, I'll have to fix `config.genomes.url2db()`:

https://github.com/RNAcentral/rnacentral-webcode/blob/80c3627e8c166a19d784bae6685ed6d141ebec83/rnacentral/portal/config/genomes.py#L286-L286

Dog and Gorilla RNAs in Genoverse track return meaningless descriptions, Dictyostelium Discoideum track is just empty:

http://localhost:8000/rna/URS00003D9803/9595
http://localhost:8000/rna/URS0000A95A54/9615
http://localhost:8000/rna/URS00005CDD41/352472

**Comment by blakesweeney** [comment]
I'm closing this in favour of #332, as that is how we will fix this issue.
