### ISSUE TITLE
Provide description without species name in the API

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#322]
PDBe would like to use RNAcentral descriptions but don't want to have species name as part of the description. We need to find a way to expose this information in the RNA entry API.

**Comment by BurkovBA** [comment]
I think, description just shouldn't contain species - in web interface I'll be adding species name to description. As for the Lucene index - I don't know.

**Comment by AntonPetrov** [comment]
That's a valid point too - maybe never have species in the description and add species on the fly when necessary.

**Comment by blakesweeney** [comment]
As an example consider this: http://rnacentral.org/rna/URS00002F9CDD/511145. Here we have the description `Escherichia coli str. K-12 substr. MG1655 tRNA-SeC (TCA)` but what they want would be `tRNA-SeC (TCA)`. In this case that could be pulled from the `product` or `standard_name` field in the db.
