### ISSUE TITLE
Allow download of sequence search results

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#347]
Analysing the results of a sequence search should be easy and simple. A quick way to do this would be to provide download the the results. This may want to wait until after #346 so that users can download a multiple sequence alignment. I suspect that is what is actually desired, not just a lot of pairwise alignments. We should also think about downloading the same formats we allow for a text search, but from the sequence search.

**Comment by AntonPetrov** [comment]
Now that the new cloud sequence search is up and running, we can revisit this task and enable the download of search results.

**nhmmer** supports the following 2 options:
```
  -A <f>             : save multiple alignment of all hits to file <f>
  --tblout <f>       : save parseable table of hits to file <f>
```

If nhmmer runs with these options, then for each sequence database chunk we will get 2 new output files. These results from all chunks need to be combined into 2 final files that should be downloadable.

This should be looked into after #484 is done.
