### ISSUE TITLE
Make the difference between a generic page and a species specific page clear

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#357]
From the SAB it seems that it is basically impossible to tell if you are looking at an species specific page or a generic page. This needs to be fixed. We may also want to consider different functionality for these pages. For example on a generic page the taxonomic tree may be more interesting than on a species specific page. Either way we must do something to distinguish these two. 

- [ ] hide publications and annotations
- [ ] provide a list of URS_taxid entries
- [ ] bring taxonomy component to the main tab

**Comment by blakesweeney** [comment]
The generic sequence pages should also be changed to not query the database for the generic precompute entries. If we do this we can start simplifying an overly complex part of the pipeline. It should be possible to simplify the pages and produce the key part, a list of species specific pages and some phylogeny infomation without it.

**Comment by carlosribas** [comment]
Done
