### ISSUE TITLE
add annotations of lncRNAs in D. melanogaster

### ISSUE THREAD

**Issue by mt1022** [RNAcentral/rnacentral-webcode#395]
Annotation of fly lncRNA is avaiable in most recent release of flybase (r6.21). About ~2,000 lncRNA genes are annotated. I hope this could be incorporated in to RNAcentral if time available.

**Comment by AntonPetrov** [comment]
@mt1022 Thank you for the suggestion! We aim to import the latest version of FlyBase in the next RNAcentral release, so stay tuned. 📻 

Please feel free to send us any other feedback RNAcentral, it is very helpful for us!

**Comment by AntonPetrov** [comment]
🎉 The latest RNAcentral release includes lncRNAs from FlyBase:
http://rnacentral.org/search?q=flybase%20AND%20rna_type:%22lncRNA%22

@mt1022 I am closing this issue but feel free to reopen it if you find any problems or submit new issues. Your input is greatly appreciated!
