### ISSUE TITLE
Genome mapping won't load for the following genomes

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#401]
Create unit-tests for these cases:

- [ ] http://rnacentral.org/rna/URS00008CAEB7/9940
- [ ] http://localhost:8000/genome-browser?species=caenorhabditis_japonica&chromosome=Cjap.Contig10011&start=3583&end=3664

**Comment by AntonPetrov** [comment]
The genome mapping works fine for these pages now.
