### ISSUE TITLE
2D tab shouldn't be returning 404 error - it scares off Google crawler

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#402]
It looks like Google crawler is scared off with 404 errors from the REST api and returns "crawl anomaly" status for such pages.

Thus 2D structure component better be refactored to handle non-existing 2D structures without returning 404 from the REST API, if we want love from Google to our sitemaps.

**Comment by AntonPetrov** [comment]
What would be a better status code to return in case there is no 2D for a sequence?

**Comment by BurkovBA** [comment]
I think, it's better to just return an empty object?
