### ISSUE TITLE
Slack hook for background jobs on the database

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#403]
When we're running off-screen jobs, maybe we should slack RNAcentral channel?

@blakesweeney, @AntonPetrov how do you think?

**Comment by blakesweeney** [comment]
I've looked into this and have an initial script that will post notifications. As I do more with nextflow I will integrate this script.

**Comment by AntonPetrov** [comment]
This seems to have been implemented so closing the issue.
