### ISSUE TITLE
Which RNA central download to use to get basic metadata?

### ISSUE THREAD

**Issue by cmungall** [RNAcentral/rnacentral-webcode#42]
I'm looking for a download that gives

 * RNA Central ID
 * Taxon ID
 * Symbol (eg HOTAIR)
 * Mappings to other IDs
 * RNA type (preferably SO)

It looks like this isn't possible as RNAC IDs are groupings of sequences from different species, so I would have to do the lookup myself. I'm super-lazy so looking for hints here to avoid multiple lookups.

For hotair RNAC has
http://rnacentral.org/rna/URS000075EF05

The website has an HGNC and an NCBIGene ID which is a good start for obtaining further metadata...

Unfortunately it looks like this is being stitched together from database calls. When I use the API to get the yaml or json it doesn't have any of this.

The best I can do is the id mapping file which has:

```
URS000075EF05   REFSEQ  NR_047518       9606
```

so I guess I can iterate through these, lookup the refseq in some genbank file or something like that, get the NCBI ID, and get the metadata I need that way... is there a better way?

**Comment by AntonPetrov** [comment]
Hi Chris,

Are you trying to get this information for all RNAcentral sequences or just a subset?

If you want to analyse the entire database, then we can look into generating a new report.

Alternatively, you could consider using the API. For example, here is a description of the sequence that you mentioned in json format:
http://rnacentral.org/api/v1/rna/URS000075EF05?flat=true

It contains a list of cross-references for each sequence with taxon id, gene name, and RNA type (not SO I am afraid).

You can download the json file from RNAcentral search. For example, if you [search for hotair gene](http://rnacentral.org/search?q=gene:%22hotair%22) you can download the json file:
http://rnacentral.org/export/results?job=36abf470-0fd6-4b60-9547-a7fc78e8e5a4

The export works best for <10,000 entries.

Let me know if the API approach suits your needs.

**Comment by cmungall** [comment]
I'm looking to get metadata for all RNAs in human and a dozen or so other species (but am happy to work with the entire db and filter what I need). Some kind of database dump would be ideal.

the flat=true json format looks more like what I need - though I note it still lacks metadata like the HGNC ID

**Comment by AntonPetrov** [comment]
The HGNC ids shown in RNAcentral actually come from RefSeq, so while it's okay to link to HGNC from RNAcentral (where possible), I don't think we are in position to distribute this data on the FTP site until we import the data from HGNC directly.

Would it help if I add RNA types and gene names to the id mapping file as new columns? I am currently working on the next RNAcentral release so I could add a new file to the production pipeline and make it available within a couple of weeks.

**Comment by cmungall** [comment]
That would be useful (although at this point it's no longer strictly an ID mapping file). This isn't super-urgent for me, so rather than making quick extensions to existing formats, if you wanted to pass on one round and gather other opinions on what users might want in a download thatw ould be fine with me.

**Comment by AntonPetrov** [comment]
Okay, sounds good. Thank you for your feedback, Chris!

I will leave this issue open and post any updates here as they become available.

**Comment by cmungall** [comment]
Any progress on this? (adding gene names and RNA types to mapping file or equivalent)

**Comment by AntonPetrov** [comment]
I will put this information in a new file based on the current mapping file. The file should appear on the FTP site by Monday Dec 11th (I'll update this thread once it's ready). Then we can review the file and see if it is worth updating it every release.

However, I have to note that gene names are quite inconsistent across databases and there is no curation on the RNAcentral side, so YMMV.

**Comment by cmungall** [comment]
On 11 Dec 2015, at 12:14, Anton Petrov wrote:

> I will put this information in a new file based on the current mapping 
> file. The file should appear on the FTP site by Monday Dec 11th (I'll 
> update this thread once it's ready).

Thanks! Will check back then (14th?)

> Then we can review the file and see if it is worth updating it every 
> release.
>
> However, I have to note that gene names are quite inconsistent across 
> databases and there is no curation on the RNAcentral side, so YMMV.

OK, I guess this is what we will have to live with

**Comment by AntonPetrov** [comment]
Yes, of course Dec 14th not 11th, sorry!

**Comment by AntonPetrov** [comment]
Please have a look at the new mapping file and let me know if you have any comments:
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/.id_mapping

**Comment by cmungall** [comment]
Thanks!

Great having the externally assigned gene symbols in col 6

Column 5:

The following are not in SO:

 * None
 * antisense_RNA lncRNA
 * lncRNA
 * misc_RNA
 * other
 * precursor_RNA

I recommend leaving the field blank for 'None' and discarding 'other'. Or you can simply use 'RNA' if you know nothing more than it's an RNA

For the others we can coordinate with SO. Or perhaps this is a SO-INSDC coordination/mapping thing.

You might want to change your example.txt to include an example with a gene symbol, e.g

```
URS0000037184   VEGA    OTTHUMT00000350154      9606    antisense_RNA   HOTAIRM1
URS0000037184   VEGA    OTTHUMG00000158089      9606
URS0000037184   ENA     HG500100.1:1..163:ncRNA 9606    lncRNA  HOTAIRM1
URS0000037184   LNCIPEDIA       lnc-EVX1-13:1   9606    lncRNA  lnc-EVX1-13
```

Looks great you can close this ticket on release or now

**Comment by AntonPetrov** [comment]
Thanks for the quick feedback!

All RNA types (including *other*) are given according to the [INSDC classification](http://www.insdc.org/rna_vocab.html), so if you come up with a good mapping or coordinate with INSDC, please let me know and I'll be sure to integrate the SO terms into RNAcentral. I will get rid of all *None* and *antisense_RNA lncRNA* during the release.

I'll close this issue once the change is deployed in RNAcentral v4 (provisionally scheduled for March 2016).

**Comment by cmungall** [comment]
btw, I notice this is slated for Release 5, which has a date of March 2017. Is this a typo?

I can keep using the test URL until then but that seems a long lag...

**Comment by AntonPetrov** [comment]
That should be March 2016, I updated the milestone. Thanks a lot!

**Comment by AntonPetrov** [comment]
The id mapping file now includes ncRNA type and gene names:
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/5.0/id_mapping/

Feel free to reopen the issue if you find any problems with the file.
