### ISSUE TITLE
Switch to using sequence_regions table for coordinates

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#438]
This sequence: https://test.rnacentral.org/rna/URS00002F21DA/7227 has a funny display for coordinates because it is pulling the coordinates from rnc_coordinates. This table is outdated and not as nice to work with as the rnc_sequence_regions table. It would help a lot if we only used the rnc_sequence_regions table to get the coordinates for mapped and given coordinates.

**Comment by AntonPetrov** [comment]
Can this be closed?

**Comment by blakesweeney** [comment]
I think @BurkovBA has made this change, yes.

**Comment by BurkovBA** [comment]
There's an issue with Annotations still using the old xrefs and rnc_coordinates table for coordinates. We need to move it to rnc_sequence_regions.

**Comment by blakesweeney** [comment]
We should make that change this release. I'm planning on removing the old tables and code to populate them for release 12.

**Comment by AntonPetrov** [comment]
✅
