### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 1746252547** [RNAcentral/rnacentral-webcode#465]
1.The example in the API can't work, just represent " 0 count",
https://www.rnacentral.org/api/v1/rna/?database=mirbase.
2.And when i use https://www.rnacentral.org/api/v1/rna/?rna_type=lncrna to ask for information only related with lncRNA, the count is 15475828 which means no filter.

With Sincerely

**Comment by blakesweeney** [comment]
Hi, thanks for pointing out the issues. I'm looking into the database filtering issue currently. Currently we do not filter by `rna_type` but that does seem reasonable. We will look into implementing it as well.

**Comment by 1746252547** [comment]
Thank you for your reply.

**Comment by 1746252547** [comment]
But how can i get all the information of lncRNA in RNAcentral ? I just cant' download all lncRNA because the limitation of 250,000.  In RNAcentral there are 737,606 information about lncRNA. I'll appreciate your help once i get your reply.

**Comment by blakesweeney** [comment]
I'm happy to provide a data dump for you, if you specify what data you want (sequences only, ids, etc). Or you can use the Postgres database to query and get anything you would like.

**Comment by blakesweeney** [comment]
As we have discussed this issue more over email, I am closing it. Please get in contact if you have more questions.
