### ISSUE TITLE
Improve download filenames

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#473]
This some feedback from a user. The current download filenames are a bit short and could be improved by making them a bit longer. They suggest another 20 characters or so. This would help users track what downloads they have.

**Comment by carlosribas** [comment]
Current download filenames are limit to 50 characters. I guess we can double this value. 

The filename length for most file systems is 255 (see https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits and https://docs.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison#limits)

How about increase the value to 100?

**Comment by blakesweeney** [comment]
That is good with me.

**Comment by carlosribas** [comment]
The new filename limit is 200
