### ISSUE TITLE
could not download 'jason' results by search

### ISSUE THREAD

**Issue by gnilihzeux** [RNAcentral/rnacentral-webcode#485]
job id       : e9326a5a-3370-49f1-863d-28363d660003
Problem  : could not download 'jason' results by search 【 TAXONOMY:"9606" AND qc_warning_found:"False" AND has_genomic_coordinates:"True" AND (rna_type:"tRNA" OR rna_type:"rRNA" OR rna_type:"snRNA" OR rna_type:"snoRNA") AND length:[20 TO 13373] 】

Thanks very much.

**Comment by AntonPetrov** [comment]
Thank you for taking the time to report this problem! We are investigating and will update this issue when the JSON export is working again 🚧

**Comment by carlosribas** [comment]
Hello @gnilihzeux,

Problem solved. You can download the results of the query `TAXONOMY:"9606" AND qc_warning_found:"False" AND has_genomic_coordinates:"True" AND (rna_type:"tRNA" OR rna_type:"rRNA" OR rna_type:"snRNA" OR rna_type:"snoRNA") AND length:[20 TO 13373]` until December 9 here: https://rnacentral.org/export/results?job=dfc9e795-bb94-4ed4-966e-b3a700293a4f

Best regards,
Carlos.
