### ISSUE TITLE
PG11 Transition

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#580]
Just a issue to track what is needed to know if we can safely move to the new pg11 databases.

- [x] Run test.rnacentral.org of pg11 prod database.
- [x] Import PDBe data to pg11 prod database.
- [x] Use delphix to update pg11 tst database with the new PDBe data.
- [x] Redeploy test.rnacentral.org to use pg11 tst database.
- [x] Update pg11 public access database using pgdump/restore.

**Comment by afg1** [comment]
PDBe import pipeline just ran to completion into the pg11 prod database. It's using some of my new rust code to do the big groupby and sort on xref, and then the selection of outdated URSs. I haven't checked the validity of the selected URSs yet, but it at least didn't cause any errors.

**Comment by afg1** [comment]
Seems I was wrong about this! The final step in the pipeline got killed in such a way that I thought it was done, but it wasn't. re-ran things this morning and still having issues - the process_range process ran for 5 hours and was killed by LSF. I'll see what I can do to make it a bit faster

**Comment by afg1** [comment]
After the import finally finished, re-ran Delphix and it completed with no warnings
