### ISSUE TITLE
Correct links to piRBase

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#582]
It seems our links to piRBase are incorrect now. As an example, https://rnacentral.org/rna/URS0000114591/7227 links to: http://www.regulatoryrna.org/database/piRNA/pirna.php?name=piR-dme-22752688, but it should be http://bigdata.ibp.ac.cn/piRBase/pirna.php?name=piR-dme-22752688.

**Comment by carlosribas** [comment]
Done
