### ISSUE TITLE
Do not parse out URS taxids from queries

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#598]
For some reason on the front end, the urs taxids in a query are parsed out. This causes an issue if there are more than one URS taxid as only the last one will be searched. For example given a query like: `URS000013F331_9606 OR URS00003D2CC9_9606` only the last urs taxid will have results shown. It is possible to work around this by surrounding the query in `()` like `(URS000013F331_9606 OR URS00003D2CC9_9606)`, but this is not user friendly. We should instead fix the parsing so we submit all urs taxids in the query and not just the last.

**Comment by carlosribas** [comment]
We had to insert the entry_type into the query after indexing other data types, so now we need to use parentheses to fix the logic. 

Just for the record, [here](https://www.ebi.ac.uk/ebisearch/ws/rest/rnacentral?query=URS000013F331_9606%20OR%20URS00003D2CC9_9606%20AND%20entry_type:%22Sequence%22) is an EBI Search query without using parentheses and [here](https://www.ebi.ac.uk/ebisearch/ws/rest/rnacentral?query=(URS000013F331_9606%20OR%20URS00003D2CC9_9606)%20AND%20entry_type:%22Sequence%22) is the same query using parentheses
