### ISSUE TITLE
miRNA 2000 nucleotides long

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#61]
[URS0000010D9A](http://rnacentral.org/rna/URS0000010D9A/7227?tab=overview) has 2,149 nts and is labeled as a miRNA.

[Underlying ENA entry](http://www.ebi.ac.uk/ena/data/view/Non-coding:EU047594.1:1..2149:ncRNA&display=text)

Actions:
- report this to ENA and update the metadata
- find a way of identifying such entries automatically

**Comment by blakesweeney** [comment]
With the recent changes on test we do not call this entry miRNA any more but precursor_RNA instead. We don't report the changes anywhere, but we probably could.

**Comment by AntonPetrov** [comment]
This has been fixed.
