### ISSUE TITLE
Is there a database production issue ?

### ISSUE THREAD

**Issue by eddelbuettel** [RNAcentral/rnacentral-webcode#622]
Something does not seem right as eg this usually works:

```sh
$ psql postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs \
        -c 'select * from xref limit 10;'
ERROR:  relation "xref" does not exist
LINE 1: select * from xref limit 10;
                      ^
$ 
$ psql  postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs 
psql (15.4 (Ubuntu 15.4-1ubuntu1), server 10.6)
Type "help" for help.

pfmegrnargs=> \d
Did not find any relations.
pfmegrnargs=> 
```

It looks like the postgresql daemon is running but maybe the database was not loaded, or moved?

**Comment by tneary** [comment]
I'm have the same issue up until a few days ago everything work fine when I connected to the postgres DB, I can still connect as I did before but the tables are not accessible, I also get:
pfmegrnargs=> \d
Did not find any relations.
pfmegrnargs=>

**Comment by carlosribas** [comment]
Thanks @eddelbuettel and @tneary for reporting this issue.

We were updating the database to match the new data and it failed part way through. I believe I have already fixed the issue, but please let me know if you still have problems.

Sorry for any inconvenience this has caused!

**Comment by eddelbuettel** [comment]
All good now!  Thanks for taking care of it!
