### ISSUE TITLE
Add ncRNA type to gpi file

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#63]
Need to map between INSDC ncRNA types and SO ncRNAs.

More information here:
https://github.com/geneontology/go-site/issues/234

**Comment by cmungall** [comment]
Any update on this? Thanks!

**Comment by blakesweeney** [comment]
Hi, just to let you know we've been doing some work improving ncRNA type (and related issues) in #111. Once this is merged in fixing this will one of our priorities. Thanks!

**Comment by blakesweeney** [comment]
Hi, @cmungall I've done some work on creating a mapping for the INSDC types to SO terms and below is my current mapping. Most of the mappings are very straight forward, however there are a few where I had to make a judgement call. I've included some notes on why I selected the SO I did. Let me know if you have any comments or changes you'd like me to make. Thanks!

- RNase_MRP_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000385
- RNase_P_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000386
- SRP_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000590
- Y_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000405
- antisense_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000644
- autocatalytically_spliced_intron: http://www.sequenceontology.org/browser/current_svn/term/SO:0000588
- guide_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000602
- hammerhead_ribozyme: http://www.sequenceontology.org/browser/current_svn/term/SO:0000380
- lncRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0001877
- miRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000276
    This term means 'some sort of RNA with no known type or function'. There
    isn't a good SO term for this at all. The best I can do is assign to it the
    'transcript' type. This is kind of wrong. These sequences are sometimes a
    processed transcript, that has been incorrectly assigned 'misc_RNA':
    http://rnacentral.org/rna/URS00004A2461/9606 (is a Y_RNA). We are probably
    best of trying to avoid the misc_RNA label as much as possible. However,
    there are times times it is truly unclear:
    http://rnacentral.org/rna/URS0000256D95/9606. Some minor browsing does show
    at least a couple sequences which are transcripts so hopefully this isn't
    too wrong. Overall we should just avoid sequences that have this term, it's
    not very informative

- ncRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000655
- misc_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000673
- other: http://www.sequenceontology.org/browser/current_svn/term/SO:0000655
    This term is assigned to the same SO term as the ncRNA class. My reason
    being that I can't find a term that is a child of ncRNA but is not a
    specific class (which is what other should mean). So I'm going up a level
    in the tree to ncRNA, which is imprecise but at least not wrong.

- precursor_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0001244
    This one is a bit tricky as the SO term is defined to be ~60-70 nt but our
    sequences may be much longer (some at ~180 nt). However, I think this is a
    good fit because many of our larger sequences are expected to form the
    hairpin that defines a pre miRNA. In addition the sequences aren't so
    long as to be a whole transcript before any processing.

- piRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0001035
- rasiRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000454
- ribozyme: http://www.sequenceontology.org/browser/current_svn/term/SO:0000374
- scRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000013
- siRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000646
- snRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000274
- snoRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000275
- telomerase_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000390
- tmRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000584
- vault_RNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000404
- rRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000252
- tRNA: http://www.sequenceontology.org/browser/current_svn/term/SO:0000253

**Comment by blakesweeney** [comment]
Hi, @cmungall have you had a chance to look over this mapping? Thanks!

**Comment by cmungall** [comment]
The ones I looked at seemed fine. Good point about the miscRNA. I made an issue in the SO tracker (linked above)

**Comment by murphyte** [comment]
FYI, I just attached the INSDC:SO mappings that we use at NCBI to this ticket:
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/378

I didn't double-check it vs. your mapping above, but most of them are pretty obvious and I'm sure they're consistent. 

For precursor_RNA, it is an over-statement to map INSDC precursor_RNA specifically to pre-miRNA. That is the most common usage within RefSeq, but there are a few other places where precursor_RNA is used so at best it requires some additional analysis to decide on the mapping.

For misc_RNA, we also map to the general SO term "transcript", or "pseudogenic_transcript" if marked up with a /pseudo qualifier. I wouldn't say "transcript" is wrong, it's just not as informative as you might like.

**Comment by murphyte** [comment]
Also note that in addition to the INSDC feature type misc_RNA, there is the /mol_type="transcribed RNA", which is used extensively within TSA:
https://www.ncbi.nlm.nih.gov/nuccore/GDAY02000562.1
https://www.ncbi.nlm.nih.gov/nuccore/IABX01000001.1

For the first case, there's a CDS feature so you can deduce that mRNA would be a more appropriate type. For the second, there is no feature annotated on the RNA, but it's reasonable to treat it the same as if it had a misc_RNA feature spanning the full length. I think we don't have any cases like that in RefSeq, and it's rare in INSDC outside of TSA so you may not need to deal with it for RNAcentral, but I figured I'd point out the wrinkle for you just in case you do need to account for it.

**Comment by blakesweeney** [comment]
Hi, @murphyte thanks for the feedback. I'll look over the mapping you gave us and make changes if needed. 

Thank you for the comments about annotations those specific annotations. We do a bit of work to select the best annotated RNA type for each sequence, hopefully this means our precursor_RNA annotations are reliable but I will have to check and change our mapping if needed. 

In general we do not import psuedogenes so I will leave the misc_RNA as transcript. I'll also make a note to use the CDS feature and the "transcribed RNA" mol_type to exclude things from import into RNAcentral. I don't think it's an issue but I haven't checked extensively. Thanks!

**Comment by keilbeck** [comment]
Chris, Terrance &Blake
Nicole @nicoleruiz  and I are looking over the mappings now.
We would add a new term to map to miscRNA if you all think it is necessary and will make sure that are definitions are inclusive of your meanings.

We will also add xrefs if they are missing.

**Comment by blakesweeney** [comment]
Hi @keilbeck and @nicoleruize, thank you for checking over the mappings. I will happily use the misc_RNA term if it exists, but I am ok without having it. From the RNAcentral perspective it is a very uninformative term and we are hoping to cut down on the numbers of sequences annotated as misc_RNA. Thanks again!

**Comment by blakesweeney** [comment]
Hi, I've looked a bit more at the things we label as precursor_RNA and I agree with @murphyte that pre-miRNA may be an overstatement. So I will move to mapping to primary_transcript like RefSeq does. One of our goals is to have a more accurate mapping so we will look into having more precise labels. Thanks for the feedback!

**Comment by AntonPetrov** [comment]
The RNAcentral GPI file now contains ncRNA types:
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/7.0/gpi/

@tonysawfordebi, sorry it took us so long!

Feel free to reopen this issue or create a new one if you notice any problems.
