### ISSUE TITLE
Human GFF

### ISSUE THREAD

**Issue by genomicsguy** [RNAcentral/rnacentral-webcode#632]
Is it possible to get a human GFF file that includes Parent attribute that links transcripts to their respective genes. The current file only links exons to transcripts. Could you also provide the code to create the GFF file, as that could allow users to more easily modify it.

**Comment by carlosribas** [comment]
Hi @genomicsguy. Unfortunately, we don't have this data at the moment, but we are working to include gene level annotations in our database. We hope to have this data available soon.

**Comment by genomicsguy** [comment]
Keep us posted - thank you!
