### ISSUE TITLE
Create xref files for each database

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#68]
Example:

```
ID1    URS0000000001
ID2    URS0000000002
```

This could make it easier for expert databases to link back to RNAcentral.

**Comment by blakesweeney** [comment]
I think the structure that is best suited to our current setup is based upon type of data. An example is (Note I haven't shown readme's and such that should be there):

```
release-8
├── cross_references
│   └── cross_references.json
└── database_mappings
    ├── ensembl_mapping.tsv
    └── mirbase_mapping.tsv
```

This is more less consistent with what we do currently where we have things organized by type of data (ie, `sequences` vs `gpi` vs `id_mapping`). So we have a `cross_references` directory that contains the json file produce in #128, and then a database specific mapping directory (`database_mappings`) that contains all mappings produce here. Also, I'm flexible on the names these are just simple examples.

This is similar to other databases like Ensembl who provide export organized by file type, ie all EMBL files together and then all FASTA files together, etc. 

I should note, this isn't the structure I first thought of when thinking about this data, I started with one organized by database like:

```
release-8
└── database_specific
    ├── README
    ├── ensembl
    │   ├── README
    │   ├── cross_references.json
    │   └── id_mapping.tsv
    └── mirbase
        ├── README
        └── id_mapping.tsv
```

but I don't want to introduce multiple different ways off organizing things in to our FTP site.

Any thoughts @AntonPetrov?

**Comment by AntonPetrov** [comment]
Thanks Blake! Would this replace the `id_mapping` folder or be a new folder? What about something like this:

```
release-8
├──id_mapping
          |______ example.txt
          |______ id_mapping.tsv.gz
          |______ readme.txt
          |______ database_mappings
                      └── ensembl__rnacentral_id_mapping.tsv
                      └── mirbase_rnacentral_id_mapping.tsv
```

**Comment by blakesweeney** [comment]
I like your setup more, lets go with that.

**Comment by AntonPetrov** [comment]
The files can be found in ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/7.0/id_mapping/database_mappings/
