### ISSUE TITLE
Improve entry descriptions

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#78]
miRBase description should be preferred to generic ENA entries.

Example: 
"dme-bantam-3p" does not appear in name of the 3p mature transcript:
http://rnacentral.org/search?q=dme-bantam-3p

**Comment by AntonPetrov** [comment]
Another example of the same issue:
http://rnacentral.org/rna/URS000045C676/3702

**Comment by blakesweeney** [comment]
I'm looking into this. I have a question about the preferred behaviour. Should we always select miRNA over others. For example look at:

http://rnacentral.org/rna/URS00004E9E38/7227
and it's precursor:

http://rnacentral.org/rna/URS00002F21DA/7227

here refseq calls the sequence: "Drosophila melanogaster (fruit fly) ban precursor RNA precursor. " while miRNA calls it: "Drosophila melanogaster (fruit fly) microRNA dme-bantam precursor " which I think is more inline with the new description of "Drosophila melanogaster (fruit fly) microRNA dme-bantam-3p". My feeling is to bias against the refseq description but I'm not sure of how this will alter other descriptions.

**Comment by AntonPetrov** [comment]
miRBase is a reference resource for miRNAs and their descriptions should be preferred. I would say that for all miRNA and miRNA precursors we should try to use miRBase descriptions first and if there are no miRBase xrefs to get descriptions from, then fallback on RefSeq, then on other databases.

**Comment by AntonPetrov** [comment]
The issues described above have been resolved so I am closing this issue.
