### ISSUE TITLE
Generate a file for Ensembl xref system

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#91]
Requirements:

* JSON format
* fields:
    * RNAcentral species-specific ids
    * MD5 checksum
    * sequence
    * description
    * ncRNA type
    * high quality xrefs (GtRNAdb, maybe Rfam seeds, do not include RefSeq because it is imported separately)

**Comment by AntonPetrov** [comment]
Example JSON entry for :

```
{
    'rnacentral_id': 'URS000067FCA5_9606',
    'description': 'Homo sapiens Small nucleolar RNA SNORA81',
    'sequence': 'ACCUUCUUGUAUAAGCACUGUGCUAAAAUUGCAGACACUAGGACCAUGUCUUGGUUUUUGCAAUAAUGCUAGCAGAGUACACACAAGAAGAAAAGUAACAGCACUAGAUUGUAAAGACUGGGGUGGACCUCUUUCUUAAUGUCCAAUGUCCUUUGUCUUAAGAUUUGGUGCAAUAUCU',
    'md5': 'ea07a553e77ded36156805894bc4767e',
    'rna_type': 'snoRNA',
    'xrefs': [
        {
          'database': 'Rfam',
          'id': 'RF01241'
        }
    ]
}
```

**Comment by nerdstrike** [comment]
@premenand17 will be the one to implement the consumer of this format, but it looks pretty sound.

**Comment by premanand17** [comment]
Curious to know if the 'Ensembl xref export' data is available to download. If not yet, could you give us a tentative date when it will be available please. Thank you.

**Comment by blakesweeney** [comment]
Hi, we are currently working on the next release of RNAcentral and expect it to be out in about a week. We will work more on this once that is finished. However, we do have some initial data exported available at: https://drive.google.com/open?id=0B8xWdphaqbUvWjhHMVR4a2kwM2s. It is a gzipped JSON file that follows the schema defined above. Please look at it and let us know if this works for your purposes.

**Comment by premanand17** [comment]
Excellent. We had a look at the json file and it looks good for us. Thank you for the updates.

**Comment by nerdstrike** [comment]
Ensembl is approaching a hard deadline on this data. We are releasing this week and will begin processing xrefs for next release in a few weeks time. Do we need to make a contingency plan around this not being available?

**Comment by AntonPetrov** [comment]
No contingency plans should be necessary. We have the json file, just need to move it to the final location. @blakesweeney can provide more info on when it's going to be ready.

**Comment by blakesweeney** [comment]
Hi,

Sorry about the slow response. Anton and I are travelling right now. The
dump files are available at:
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/7.0/json/

The files are named as ensembl-xrefs-min-max.json. I may have generated
some files with duplicate entries, that is exported the same URS more
than once  but this should cover all sequences.

Please let us know if there are any issues with the export.

Thanks!
Blake Sweeney


Blake Sweeney, PhD
Bioinformatician
European Bioinformatics Institute (EMBL-EBI)
Phone: +44 (0)1223 4359 Email: bsweeney@ebi.ac.uk
http://rnacentral.org/

**Comment by AntonPetrov** [comment]
Closing this issue as the work has been completed but feel free to reopen if necessary.
