### ISSUE TITLE
Improving HGNC import

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#93]
- [x] As pointed out in #92 it would probably be better to use `first` instead of `all` and then getting the first result, if any. We should fix this for the next release. 

- [x] Capitalise descriptions for consistency with other databases. Example: `long intergenic non-protein coding RNA 1105` should be `Long intergenic non-protein coding RNA 1105`.

- [x] Add "Homo sapiens" to all descriptions for consistency with other descriptions.

**Comment by AntonPetrov** [comment]
The improvements are in the `release-7` branch.
