### ISSUE TITLE
Import more lncRNAdb xrefs

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#97]
Currently only 62 lncRNAdb entries are imported into RNAcentral. Many more entries are not imported yet. It would be very useful to import more xrefs to lncRNAdb.

I mapped a lot of lncRNAdb entries to HGNC, and HGNC added most of these xrefs to their database. So now that we have HGNC in RNAcentral, we can import lncRNAdb entries that match HGNC as well. This will add ~150 human lncRNAs.

Many lncRNAdb entries are not from human and they can't be mapped like this. We need to explore what other accessions from lncRNAdb can be used to find matching entries in RNAcentral.

**Comment by blakesweeney** [comment]
They have provided all data to us and actually just link to our page instead of having their own website.
